Enhancement/wieldable decouple
Phazorknight/Cogito pull request #151
Opened 2024-04-06 12:11 UTC by brian-holsters

Solves: #150

2024-04-07 18:28 UTC, Phazorknight requested changes
Requested a change to Throwables defaulting to the pickup scene as the projectile. otherwise this looks solid.

2024-04-07 18:28 UTC, Phazorknight commented on COGITO/Wieldables/Wieldable_Throwable.gd
Projectile spawning:
I would not default to the projectile prefab being the same as the pickup item.
I can see cases where devs might want a the spawned projectile be a different scene than the pickup-item
(items which thrown state would differ from their pickup item state, something like armed grenades for example).

2024-04-08 06:36 UTC, brian-holsters commented on COGITO/Wieldables/Wieldable_Throwable.gd
solved by adding an optional export to the wieldable script, here's a video of it working:

https://streamable.com/i9i99n

2024-04-08 19:07 UTC, Phazorknight approved these changes

2024-04-08 19:09 UTC, merged