Simplifies PlayerInteractionComponent
Phazorknight/Cogito pull request #169
Opened 2024-04-18 08:07 UTC by aronand

Simplifies PlayerInteractionComponent by merging input checks for interact and interact2 to a single block.
Removes a RayCast3D.is_colliding() check and gets that information via RayCast3D.get_collider() (null if no collision).

2024-04-18 08:10 UTC, aronand commented on COGITO/Components/PlayerInteractionComponent.gd
> +		var action: String = "interact" if event.is_action_pressed("interact") else "interact2"
Input and InputEvent don't seem to have a way to return the action name, thus a bit hacky way of getting the action name. Needs a different solution if more interaction keys are introduced, or moving the interaction check to Node._process() instead.

2024-04-18 09:49 UTC, aronand commented on COGITO/Components/PlayerInteractionComponent.gd
> -					inventory.remove_item_from_stack(slot)
InventoryPD.remove_item_from_stack() consumes one item at a time, making this loop take longer than is necessary. A possible refactor to it would be to allow the user to define the amount to remove as well.

2024-04-19 08:43 UTC, Phazorknight requested changes
Overall this does some nice cleanups.

There's an issue though with the changes to the reload: It seems like the reload_amount properties of AmmoItemPD is not considered, thus a battery is just adding 1 to the charge of the flashlight. Or the clip of the Laser Rifle is just adding 1 to the Laser Rifle charge.

Would you be able to fix this?

2024-04-19 09:32 UTC, aronand commented
Good catch! I'll have a look during the weekend.

2024-04-20 12:55 UTC, aronand commented
Fix is in now. Tested both the flashlight and the laser rifle, which now seem to function as intended.

2024-04-30 16:25 UTC, Phazorknight approved these changes
Looks good, thanks!

2024-04-30 16:26 UTC, merged